### ISSUE TITLE
Zookeeper compatibility issue

### ISSUE THREAD

**Issue by robbytx** [bazaarvoice/curator-extensions#42]
https://github.com/bazaarvoice/curator-extensions/commit/7a0c200494316eb4f33eab097f92b945eb955bc6 upgraded to Apache Curator 4.x, which declares a dependency on the (beta) Zookeeper 3.5.x client library, which appears to have compatibility problems with Zookeeper 3.4.x servers.

In particular, using version 1.5.2 of this library with Curator 4.0.1 and ZK 3.5.4-beta against a 3.4.x server, we've experience a hang with:
```
"PersistentEphemeralNodeThread-1" id=35 state=TIMED_WAITING
    - waiting on <0x16556aa0> (a java.util.concurrent.CountDownLatch$Sync)
    - locked <0x16556aa0> (a java.util.concurrent.CountDownLatch$Sync)
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
    at org.apache.curator.CuratorZookeeperClient.internalBlockUntilConnectedOrTimedOut(CuratorZookeeperClient.java:394)
    at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:56)
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
    at org.apache.curator.framework.imps.CreateBuilderImpl.findProtectedNodeInForeground(CreateBuilderImpl.java:1240)
    at org.apache.curator.framework.imps.CreateBuilderImpl.access$1800(CreateBuilderImpl.java:49)
    at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1168)
    at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158)
    at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
    at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155)
    at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
    at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
    at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49)
    at com.bazaarvoice.curator.recipes.PersistentEphemeralNode$Sync.createNode(PersistentEphemeralNode.java:287)
    at com.bazaarvoice.curator.recipes.PersistentEphemeralNode$Sync.access$900(PersistentEphemeralNode.java:241)
    at com.bazaarvoice.curator.recipes.PersistentEphemeralNode$Async$2.run(PersistentEphemeralNode.java:168)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

Per http://curator.apache.org/zk-compatibility.html, the proper way to maintain compatibility with 3.4.x servers is to exclude the 3.5.x ZK dependency from the Curator library (or this library), and include the 3.4.x ZK dependency instead.

Since this poses a problem for adopting version 1.5.2+ of this library (or version 1.10.2 of https://github.com/bazaarvoice/ostrich), this compatibility issue should be clearly stated in the README (of both projects).

**Comment by robbytx** [comment]
@ohhatiya Would you be willing to address this?

**Comment by robbytx** [comment]
After further investigation, it appears that https://github.com/bazaarvoice/curator-extensions/blob/curator-extensions-1.5.2/pom.xml includes exactly the stated workaround, so the problem actually lies with the RequireUpperBoundDeps rule not honoring the exclusion:
```
[WARNING] Rule 3: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.apache.zookeeper:zookeeper:3.4.13 paths to dependency are:
  +-com.bazaarvoice....
    +-com.bazaarvoice.curator:recipes:1.5.2 (managed) <-- com.bazaarvoice.curator:recipes:1.4.4
      +-org.apache.zookeeper:zookeeper:3.4.13
and
  +-com.bazaarvoice....
    +-com.bazaarvoice.curator:recipes:1.5.2 (managed) <-- com.bazaarvoice.curator:recipes:1.4.4
      +-org.apache.curator:curator-recipes:4.0.1
        +-org.apache.curator:curator-framework:4.0.1
          +-org.apache.curator:curator-client:4.0.1
            +-org.apache.zookeeper:zookeeper:3.5.3-beta
]
```
